APPLICATION_RULES = [
    # === JAVASCRIPT VULNERABILITIES ===
    {
        "category": "xss",
        "name": "DOM XSS - innerHTML",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html", ".htm"],
        "vuln_patterns": [
            r"\.innerHTML\s*=",
            r"\.outerHTML\s*=",
            r"document\.write\s*\(",
            r"\.insertAdjacentHTML\s*\(",
            r"dangerouslySetInnerHTML",
            r"v-html\s*=",
        ],
        "sanitizer_patterns": [
            r"textContent\s*=",
            r"innerText\s*=",
            r"DOMPurify",
            r"sanitize",
            r"escape\s*\(",
        ],
        "vuln_desc": "DOM XSS via unsafe DOM manipulation",
        "safe_desc": "Using safe DOM methods",
        "severity": "HIGH",
        "confidence": 85,
        "cwe": "CWE-79"
    },
    {
        "category": "secrets",
        "name": "Hardcoded API Keys in JavaScript",
        "file_exts": [".js", ".jsx", ".ts", ".tsx"],
        "vuln_patterns": [
            r"api[_-]?key\s*[:=]\s*['\"][^'\"]+['\"]",
            r"secret\s*[:=]\s*['\"][^'\"]+['\"]",
            r"token\s*[:=]\s*['\"][^'\"]+['\"]",
            r"password\s*[:=]\s*['\"][^'\"]+['\"]",
            r"AKIA[0-9A-Z]{16}",
            r"sk-[a-zA-Z0-9]{20,}",
        ],
        "sanitizer_patterns": [
            r"process\.env\.",
            r"import\.meta\.env",
            r"window\.env",
            r"REACT_APP_",
            r"NEXT_PUBLIC_",
        ],
        "vuln_desc": "Hardcoded API key or secret in client code",
        "safe_desc": "Using environment variables for secrets",
        "severity": "CRITICAL",
        "confidence": 90,
        "cwe": "CWE-798"
    },
    {
        "category": "network",
        "name": "Insecure HTTP Requests",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html"],
        "vuln_patterns": [
            r"fetch\s*\(\s*['\"]http://",
            r"axios\.(get|post)\s*\(\s*['\"]http://",
            r"\$\.(get|post|ajax)\s*\(\s*['\"]http://",
            r"new\s+WebSocket\s*\(\s*['\"]ws://",
            r"XMLHttpRequest.*http://",
        ],
        "sanitizer_patterns": [
            r"https://",
            r"wss://",
        ],
        "vuln_desc": "Insecure HTTP or WebSocket connection",
        "safe_desc": "Using secure HTTPS/WSS",
        "severity": "MEDIUM",
        "confidence": 75,
        "cwe": "CWE-319"
    },
    {
        "category": "codeExecution",
        "name": "Dangerous Code Execution",
        "file_exts": [".js", ".jsx", ".ts", ".tsx"],
        "vuln_patterns": [
            r"eval\s*\(",
            r"new\s+Function\s*\(",
            r"Function\s*\(",
            r"setTimeout\s*\(\s*['\"]",
            r"setInterval\s*\(\s*['\"]",
        ],
        "sanitizer_patterns": [
            r"JSON\.parse",
            r"validator",
            r"sanitize",
        ],
        "vuln_desc": "Dangerous code execution (eval, Function)",
        "safe_desc": "Using safe alternatives",
        "severity": "CRITICAL",
        "confidence": 90,
        "cwe": "CWE-94"
    },
    {
        "category": "cors",
        "name": "Wildcard CORS Configuration",
        "file_exts": [".js", ".json", ".py"],
        "vuln_patterns": [
            r"Access-Control-Allow-Origin\s*:\s*\*",
            r"origin\s*:\s*['\"]\*['\"]",
            r"allow_origins\s*=\s*\[['\"]\*['\"]\]",
        ],
        "sanitizer_patterns": [
            r"Access-Control-Allow-Origin:\s*https://",
            r"origin:\s*['\"][^'\"]+['\"]",
        ],
        "vuln_desc": "Wildcard CORS allows any domain",
        "safe_desc": "CORS restricted to specific domains",
        "severity": "MEDIUM",
        "confidence": 80,
        "cwe": "CWE-346"
    },
    
    # === ORIGINAL RULES BELOW ===
    # ... keep your existing rules here ...
]
"""
Application Rules - Authentication, Authorization, Input Validation, etc.
"""

APPLICATION_RULES = [
    # Authentication
    {
        "category": "authentication",
        "name": "Weak Hashing or Hardcoded Credentials",
        "file_exts": [".py", ".js", ".jsx", ".ts", ".tsx", ".json", ".yml", ".yaml"],
        "vuln_patterns": [
            r"password\s*=\s*['\"][^'\"]+['\"]",
            r"hashlib\.md5\(",
            r"hashlib\.sha1\(",
            r"crypto\.createHash\s*\(\s*['\"](md5|sha1)['\"]",
            r"bcrypt\.compare\s*\(\s*['\"][^'\"]+['\"]\s*,\s*['\"][^'\"]+['\"]\s*\)",
        ],
        "sanitizer_patterns": [
            r"bcrypt\.",
            r"argon2\.",
            r"pbkdf2",
            r"sha256",
            r"sha512",
            r"os\.environ",
            r"process\.env",
            r"getpass",
            r"dotenv",
        ],
        "vuln_desc": "Hardcoded credential or weak cryptographic hashing (MD5/SHA1)",
        "safe_desc": "Proper production hashing or externalized secrets used",
        "severity": "CRITICAL",
        "confidence": 85,
        "cwe": "CWE-798"
    },
    # Authorization
    {
        "category": "authorization",
        "name": "Missing Authorization Check",
        "file_exts": [".py", ".js", ".jsx", ".tsx", ".java", ".go"],
        "vuln_patterns": [
            r"@app\.route\s*\(\s*['\"][^'\"]+['\"]\s*\)",
            r"router\.(get|post|put|delete|patch)\s*\(",
            r"app\.(get|post|put|delete|patch)\s*\(",
            r"express\.Router\s*\(\s*\)",
            r"@GetMapping|@PostMapping|@PutMapping|@DeleteMapping",
        ],
        "sanitizer_patterns": [
            r"@login_required",
            r"@roles_required",
            r"@permission_required",
            r"@requires_auth",
            r"@authenticated",
            r"check_permission",
            r"auth_middleware",
            r"middleware",
            r"@PreAuthorize",
        ],
        "vuln_desc": "Exposed endpoint lacking access control checks",
        "safe_desc": "Endpoint securely protected via authorization wrappers",
        "severity": "HIGH",
        "confidence": 80,
        "cwe": "CWE-862"
    },
    # Session Management
    {
        "category": "sessionManagement",
        "name": "Insecure Cookie or JWT Configuration",
        "file_exts": [".py", ".js", ".ts", ".java"],
        "vuln_patterns": [
            r"set_cookie\s*\(",
            r"cookies\.set\s*\(",
            r"jwt\.decode\s*\(.*verify\s*=\s*False",
            r"jwt\.verify\s*\(\s*false",
            r"res\.cookie\s*\([^,]+,\s*[^,]+,\s*{[^}]*secure\s*:\s*false",
        ],
        "sanitizer_patterns": [
            r"httponly\s*=\s*True",
            r"httpOnly\s*:\s*true",
            r"secure\s*=\s*True",
            r"secure\s*:\s*true",
            r"samesite\s*=\s*['\"]strict['\"]",
            r"samesite\s*:\s*['\"]strict['\"]",
            r"verify\s*=\s*True",
            r"verify\s*:\s*true",
        ],
        "vuln_desc": "Insecure cookie flags (HttpOnly/Secure missing) or unverified JWT",
        "safe_desc": "Cookie flags set properly and JWT cryptographically verified",
        "severity": "HIGH",
        "confidence": 80,
        "cwe": "CWE-614"
    },
    # User Inputs
    {
        "category": "userInputs",
        "name": "Unsanitized Dynamic Code Execution",
        "file_exts": [".py", ".js", ".jsx", ".ts", ".tsx", ".php", ".rb"],
        "vuln_patterns": [
            r"\beval\s*\(",
            r"\bexec\s*\(",
            r"subprocess\.(Popen|run|call)\s*\(",
            r"system\s*\(",
            r"popen\s*\(",
            r"new\s+Function\s*\(",
            r"Function\s*\(",
            r"setTimeout\s*\(\s*['\"]",
            r"setInterval\s*\(\s*['\"]",
        ],
        "sanitizer_patterns": [
            r"int\s*\(",
            r"float\s*\(",
            r"shlex\.quote",
            r"escape\s*\(",
            r"validation",
            r"sanitize\s*\(",
            r"ast\.literal_eval",
            r"json\.loads",
        ],
        "vuln_desc": "Dynamic code execution from user input (eval, exec, system)",
        "safe_desc": "Dynamic parameters validated and sanitized before execution",
        "severity": "CRITICAL",
        "confidence": 90,
        "cwe": "CWE-94"
    },
    # XSS
    {
        "category": "xss",
        "name": "DOM XSS via Unsafe DOM Manipulation",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html", ".htm", ".vue"],
        "vuln_patterns": [
            r"\.innerHTML\s*=",
            r"\.outerHTML\s*=",
            r"document\.write\s*\(",
            r"document\.writeln\s*\(",
            r"\.insertAdjacentHTML\s*\(",
            r"dangerouslySetInnerHTML",
            r"v-html\s*=",
            r"ng-bind-html",
            r"\.appendChild\s*\(\s*document\.createElement",
            r"\.createElement\s*\(\s*['\"]script['\"]\s*\)",
            r"javascript:",
        ],
        "sanitizer_patterns": [
            r"textContent\s*=",
            r"innerText\s*=",
            r"DOMPurify\.sanitize",
            r"sanitize\s*\(",
            r"escape\s*\(",
            r"encodeURIComponent\s*\(",
            r"encodeURI\s*\(",
            r"\.createTextNode\s*\(",
            r"validator\.escape",
            r"sanitize-html",
        ],
        "vuln_desc": "DOM-based XSS via unsafe DOM manipulation methods",
        "safe_desc": "DOM manipulation uses safe methods or proper sanitization",
        "severity": "HIGH",
        "confidence": 85,
        "cwe": "CWE-79"
    },
    # SQL Injection
    {
        "category": "injection",
        "name": "SQL Injection via String Concatenation",
        "file_exts": [".py", ".js", ".php", ".java", ".go", ".rb"],
        "vuln_patterns": [
            r"SELECT.*\+.*\+.*FROM",
            r"execute\s*\(\s*['\"]%s.*['\"]\s*%",
            r"query\s*\(\s*['\"]\+.*\+['\"]",
            r"WHERE\s+\w+\s*=\s*['\"]?\s*\+\s*\w+",
            r"f['\"]SELECT.*\{.*\}.*",
            r"\$\{.*\}.*sql",
        ],
        "sanitizer_patterns": [
            r"\.execute\s*\([^,]+,\s*\(",
            r"prepared\s*statement",
            r"\.escape\s*\(",
            r"\.format\s*\(\s*\[",
            r"\.cursor\.execute\s*\(\s*['\"].*%s.*['\"],\s*\(",
            r"sequelize",
            r"sqlalchemy\.",
            r"\.raw\s*\(",
        ],
        "vuln_desc": "SQL injection via string concatenation or string formatting",
        "safe_desc": "Using parameterized queries or ORM",
        "severity": "CRITICAL",
        "confidence": 85,
        "cwe": "CWE-89"
    },
    # GraphQL
    {
        "category": "graphql",
        "name": "GraphQL Query Injection",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".py", ".java"],
        "vuln_patterns": [
            r"gql\s*`[^`]*\$\{",
            r"gql\s*\(`[^`]*\$\{",
            r"graphql\s*`[^`]*\$\{",
            r"\.query\s*\(\s*`[^`]*\$\{",
            r"\.mutate\s*\(\s*`[^`]*\$\{",
        ],
        "sanitizer_patterns": [
            r"variables\s*:",
            r"variableValues",
            r"\.setVariable",
            r"\.query\s*\([^,]+,\s*\{",
            r"\.mutate\s*\([^,]+,\s*\{",
        ],
        "vuln_desc": "GraphQL injection via string interpolation",
        "safe_desc": "Using GraphQL variables for parameterized queries",
        "severity": "HIGH",
        "confidence": 80,
        "cwe": "CWE-89"
    },
    # SSRF
    {
        "category": "ssrf",
        "name": "Server-Side Request Forgery Risk",
        "file_exts": [".py", ".js", ".ts", ".java", ".go"],
        "vuln_patterns": [
            r"requests\.(get|post|put|delete)\s*\(\s*['\"]http",
            r"fetch\s*\(\s*['\"]http",
            r"axios\.(get|post)\s*\(\s*['\"]http",
            r"urllib\.request\.urlopen\s*\(",
            r"http\.request\s*\(",
            r"request\s*\(\s*['\"]http",
        ],
        "sanitizer_patterns": [
            r"validate_url\s*\(",
            r"is_valid_url\s*\(",
            r"allowlist",
            r"whitelist",
            r"parse_url\s*\(",
            r"URL\s*\(\s*['\"]https?:\/\/[^'\"\s]+\s*\)",
        ],
        "vuln_desc": "Potential SSRF via external URL fetch without validation",
        "safe_desc": "URLs validated against allowlist before fetching",
        "severity": "HIGH",
        "confidence": 75,
        "cwe": "CWE-918"
    },
    # Secrets
    {
        "category": "secrets",
        "name": "Hardcoded API Keys and Tokens",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".py", ".json", ".yml", ".yaml"],
        "vuln_patterns": [
            r"(api_key|apikey|secret|token|password|key|auth)\s*[:=]\s*['\"][A-Za-z0-9_\-]{20,}['\"]",
            r"AKIA[0-9A-Z]{16}",
            r"sk-[a-zA-Z0-9]{20,}",
            r"gh[pousr]_[a-zA-Z0-9]{36,}",
            r"xox[baprs]-[a-zA-Z0-9-]+",
            r"eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}",
            r"firebase:.*?\{.*?apiKey",
        ],
        "sanitizer_patterns": [
            r"process\.env\.",
            r"import\.meta\.env",
            r"window\.env",
            r"REACT_APP_",
            r"VUE_APP_",
            r"NEXT_PUBLIC_",
            r"VITE_",
            r"getenv\s*\(",
            r"os\.getenv",
            r"dotenv",
            r"localStorage\.getItem",
            r"sessionStorage\.getItem",
        ],
        "vuln_desc": "Hardcoded credentials or API keys in code",
        "safe_desc": "Credentials loaded from environment variables or secure storage",
        "severity": "CRITICAL",
        "confidence": 90,
        "cwe": "CWE-798"
    },
    # File Operations
    {
        "category": "fileOperations",
        "name": "Unsafe File Operations",
        "file_exts": [".py", ".js", ".ts", ".php", ".java"],
        "vuln_patterns": [
            r"open\s*\([^,]+,\s*['\"]w['\"]\)",
            r"fs\.writeFile\s*\(\s*[^,]+,\s*[^,]+,\s*['\"]w['\"]",
            r"file_put_contents\s*\(",
            r"send_file\s*\(",
            r"send_from_directory\s*\(",
            r"fs\.readFile\s*\(\s*[^,]+,\s*['\"]?r?['\"]?\s*\)",
        ],
        "sanitizer_patterns": [
            r"tempfile\.",
            r"os\.path\.join",
            r"shutil\.",
            r"path\.join",
            r"secure_filename",
            r"safe_join",
            r"werkzeug\.utils",
            r"path\.resolve",
        ],
        "vuln_desc": "Unsafe file operations or path traversal risk",
        "safe_desc": "Using safe file handling methods",
        "severity": "HIGH",
        "confidence": 75,
        "cwe": "CWE-22"
    },
    # WebSockets
    {
        "category": "network",
        "name": "Insecure WebSocket Connection",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html"],
        "vuln_patterns": [
            r"new\s+WebSocket\s*\(\s*['\"]ws://",
            r"\.connect\s*\(\s*['\"]ws://",
            r"new\s+WebSocket\s*\(\s*['\"]http://",
        ],
        "sanitizer_patterns": [
            r"wss://",
            r"WebSocket\s*\(\s*['\"]wss://",
            r"secure\s*:\s*true",
            r"ssl\s*:\s*true",
        ],
        "vuln_desc": "Insecure WebSocket connection (should use WSS://)",
        "safe_desc": "Using secure WebSocket connection",
        "severity": "HIGH",
        "confidence": 80,
        "cwe": "CWE-319"
    },
    # HTTP Mixed Content
    {
        "category": "network",
        "name": "Mixed Content (HTTP requests from HTTPS page)",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html", ".htm"],
        "vuln_patterns": [
            r"fetch\s*\(\s*['\"]http://",
            r"axios\.(get|post|put|delete)\s*\(\s*['\"]http://",
            r"\$\.(get|post|ajax)\s*\(\s*['\"]http://",
            r"XMLHttpRequest.*http://",
            r"\.open\s*\(\s*['\"]GET['\"]\s*,\s*['\"]http://",
        ],
        "sanitizer_patterns": [
            r"https://",
            r"//",
            r"process\.env\.API_URL",
            r"window\.location\.protocol",
            r"baseURL",
        ],
        "vuln_desc": "HTTP requests from HTTPS page (mixed content)",
        "safe_desc": "Using HTTPS for secure communication",
        "severity": "MEDIUM",
        "confidence": 75,
        "cwe": "CWE-319"
    },
]