"""
Application Rules - For scanning live websites
"""

APPLICATION_RULES = [
    # === JAVASCRIPT VULNERABILITIES (For Live Websites) ===
    {
        "category": "xss",
        "name": "DOM XSS - Unsafe DOM Manipulation",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html", ".htm"],
        "vuln_patterns": [
            r"\.innerHTML\s*=",
            r"\.outerHTML\s*=",
            r"document\.write\s*\(",
            r"document\.writeln\s*\(",
            r"\.insertAdjacentHTML\s*\(",
            r"dangerouslySetInnerHTML",
            r"v-html\s*=",
            r"ng-bind-html\s*=",
            r"\.appendChild\s*\(\s*document\.createElement",
            r"\.createElement\s*\(\s*['\"]script['\"]\s*\)",
            r"javascript:",
            r"location\.href\s*=\s*['\"]javascript:",
            r"window\.location\s*=\s*['\"]javascript:",
        ],
        "sanitizer_patterns": [
            r"textContent\s*=",
            r"innerText\s*=",
            r"DOMPurify",
            r"sanitize\s*\(",
            r"escape\s*\(",
            r"encodeURIComponent\s*\(",
            r"\.createTextNode\s*\(",
            r"validator\.escape",
        ],
        "vuln_desc": "DOM-based XSS via unsafe DOM manipulation methods",
        "safe_desc": "Using safe DOM methods or sanitization",
        "severity": "HIGH",
        "confidence": 80,
        "cwe": "CWE-79"
    },
    {
        "category": "secrets",
        "name": "Hardcoded API Keys and Tokens",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".json", ".env"],
        "vuln_patterns": [
            r"api[_-]?key\s*[:=]\s*['\"][^'\"]+['\"]",
            r"secret\s*[:=]\s*['\"][^'\"]+['\"]",
            r"token\s*[:=]\s*['\"][^'\"]+['\"]",
            r"password\s*[:=]\s*['\"][^'\"]+['\"]",
            r"auth\s*[:=]\s*['\"][^'\"]+['\"]",
            r"AKIA[0-9A-Z]{16}",
            r"sk-[a-zA-Z0-9]{20,}",
            r"gh[pousr]_[a-zA-Z0-9]{36,}",
            r"xox[baprs]-[a-zA-Z0-9-]+",
            r"eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}",
            r"[\"'][A-Za-z0-9+/]{40}[\"']",
        ],
        "sanitizer_patterns": [
            r"process\.env\.",
            r"import\.meta\.env",
            r"window\.env",
            r"REACT_APP_",
            r"NEXT_PUBLIC_",
            r"VUE_APP_",
            r"VITE_",
            r"getenv\s*\(",
            r"os\.getenv",
            r"dotenv",
        ],
        "vuln_desc": "Hardcoded API key, token, or secret in client-side code",
        "safe_desc": "Using environment variables for secrets",
        "severity": "CRITICAL",
        "confidence": 85,
        "cwe": "CWE-798"
    },
    {
        "category": "network",
        "name": "Insecure HTTP/WebSocket Connections",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".html"],
        "vuln_patterns": [
            r"fetch\s*\(\s*['\"]http://",
            r"axios\.(get|post|put|delete|patch)\s*\(\s*['\"]http://",
            r"\$\.(get|post|ajax|getJSON)\s*\(\s*['\"]http://",
            r"XMLHttpRequest.*http://",
            r"new\s+WebSocket\s*\(\s*['\"]ws://",
            r"\.open\s*\(\s*['\"]GET['\"]\s*,\s*['\"]http://",
            r"new\s+Request\s*\(\s*['\"]http://",
        ],
        "sanitizer_patterns": [
            r"https://",
            r"wss://",
            r"//",
            r"process\.env\.API_URL",
            r"window\.location\.protocol",
            r"baseURL",
        ],
        "vuln_desc": "Insecure HTTP or WebSocket connection (should use HTTPS/WSS)",
        "safe_desc": "Using secure HTTPS/WSS connections",
        "severity": "MEDIUM",
        "confidence": 75,
        "cwe": "CWE-319"
    },
    {
        "category": "codeExecution",
        "name": "Dangerous Code Execution",
        "file_exts": [".js", ".jsx", ".ts", ".tsx"],
        "vuln_patterns": [
            r"eval\s*\(",
            r"new\s+Function\s*\(",
            r"Function\s*\(",
            r"setTimeout\s*\(\s*['\"]",
            r"setInterval\s*\(\s*['\"]",
            r"import\s*\(\s*['\"]",
            r"require\s*\(\s*['\"]",
            r"vm\.runInContext",
            r"vm\.runInNewContext",
        ],
        "sanitizer_patterns": [
            r"JSON\.parse",
            r"validator",
            r"sanitize",
            r"escape",
            r"int\s*\(",
            r"float\s*\(",
        ],
        "vuln_desc": "Dangerous code execution (eval, Function, setTimeout with string)",
        "safe_desc": "Using safe alternatives",
        "severity": "CRITICAL",
        "confidence": 90,
        "cwe": "CWE-94"
    },
    {
        "category": "cors",
        "name": "Wildcard CORS Configuration",
        "file_exts": [".js", ".json", ".py", ".conf"],
        "vuln_patterns": [
            r"Access-Control-Allow-Origin\s*:\s*\*",
            r"origin\s*:\s*['\"]\*['\"]",
            r"allow_origins\s*=\s*\[['\"]\*['\"]\]",
            r"origins\s*:\s*\[['\"]\*['\"]\]",
            r"cors\s*\(\s*\{[^}]*origin\s*:\s*['\"]\*['\"]",
        ],
        "sanitizer_patterns": [
            r"Access-Control-Allow-Origin:\s*https://",
            r"origin:\s*['\"][^'\"]+['\"]",
            r"allow_origins\s*=\s*\[[^\*]+\]",
            r"verify_origin",
        ],
        "vuln_desc": "Wildcard CORS allows any domain to access resources",
        "safe_desc": "CORS restricted to specific domains",
        "severity": "MEDIUM",
        "confidence": 80,
        "cwe": "CWE-346"
    },
    {
        "category": "logging",
        "name": "Sensitive Data in Console Logs",
        "file_exts": [".js", ".jsx", ".ts", ".tsx"],
        "vuln_patterns": [
            r"console\.(log|info|debug|warn|error)\s*\(\s*.*?(password|token|secret|key|credit|ssn)",
            r"console\.dir\s*\(\s*.*?(password|token|secret)",
            r"console\.table\s*\(\s*.*?(password|token|secret)",
        ],
        "sanitizer_patterns": [
            r"process\.env\.NODE_ENV\s*===?\s*['\"]development['\"]",
            r"__DEV__",
            r"logger\.(info|debug)",
            r"debug\s*\(",
        ],
        "vuln_desc": "Sensitive data logged to browser console",
        "safe_desc": "Sensitive data filtered from logs",
        "severity": "MEDIUM",
        "confidence": 75,
        "cwe": "CWE-532"
    },
    {
        "category": "debug",
        "name": "Development Mode in Production",
        "file_exts": [".js", ".jsx", ".ts", ".tsx", ".json"],
        "vuln_patterns": [
            r"debug\s*:\s*true",
            r"NODE_ENV\s*===?\s*['\"]development['\"]",
            r"process\.env\.NODE_ENV\s*!==?\s*['\"]production['\"]",
            r"if\s*\(\s*process\.env\.NODE_ENV\s*===?\s*['\"]development['\"]",
            r"__DEV__\s*===?\s*true",
            r"DEBUG\s*=\s*true",
        ],
        "sanitizer_patterns": [
            r"production\s*===?\s*process\.env\.NODE_ENV",
            r"process\.env\.NODE_ENV\s*===?\s*['\"]production['\"]",
            r"__PROD__",
            r"debug\s*:\s*false",
        ],
        "vuln_desc": "Development mode active in production code",
        "safe_desc": "Development mode disabled in production",
        "severity": "HIGH",
        "confidence": 85,
        "cwe": "CWE-489"
    },
    {
        "category": "graphql",
        "name": "GraphQL Query Injection",
        "file_exts": [".js", ".jsx", ".ts", ".tsx"],
        "vuln_patterns": [
            r"gql\s*`[^`]*\$\{",
            r"gql\s*\(`[^`]*\$\{",
            r"graphql\s*`[^`]*\$\{",
            r"\.query\s*\(\s*`[^`]*\$\{",
            r"\.mutate\s*\(\s*`[^`]*\$\{",
        ],
        "sanitizer_patterns": [
            r"variables\s*:",
            r"variableValues",
            r"\.setVariable",
            r"\.query\s*\([^,]+,\s*\{",
            r"\.mutate\s*\([^,]+,\s*\{",
        ],
        "vuln_desc": "GraphQL injection via string interpolation",
        "safe_desc": "Using GraphQL variables for parameterized queries",
        "severity": "HIGH",
        "confidence": 80,
        "cwe": "CWE-89"
    },
    {
        "category": "ssrf",
        "name": "Potential SSRF via External Fetch",
        "file_exts": [".js", ".jsx", ".ts", ".tsx"],
        "vuln_patterns": [
            r"fetch\s*\(\s*['\"]http",
            r"axios\.(get|post)\s*\(\s*['\"]http",
            r"request\s*\(\s*['\"]http",
            r"got\s*\(\s*['\"]http",
            r"node-fetch\s*\(\s*['\"]http",
        ],
        "sanitizer_patterns": [
            r"validateUrl\s*\(",
            r"isValidUrl\s*\(",
            r"allowlist",
            r"whitelist",
            r"parseUrl\s*\(",
            r"URL\s*\(",
        ],
        "vuln_desc": "Potential SSRF via external URL fetch without validation",
        "safe_desc": "URLs validated against allowlist before fetching",
        "severity": "HIGH",
        "confidence": 75,
        "cwe": "CWE-918"
    },
    {
        "category": "webhooks",
        "name": "Webhook Signature Bypass",
        "file_exts": [".py", ".js", ".ts"],
        "vuln_patterns": [
            r"webhook",
            r"stripe_webhook",
            r"github_webhook",
            r"webhook_handler",
            r"webhook_receiver",
        ],
        "sanitizer_patterns": [
            r"signature",
            r"hmac",
            r"verify",
            r"construct_event",
            r"validate_signature",
        ],
        "vuln_desc": "Webhook handler without signature verification",
        "safe_desc": "Webhook events verified with signatures",
        "severity": "HIGH",
        "confidence": 75,
        "cwe": "CWE-345"
    },
    {
        "category": "fileUploads",
        "name": "Insecure File Upload Handling",
        "file_exts": [".py", ".js", ".ts"],
        "vuln_patterns": [
            r"request\.files",
            r"file\.save\(",
            r"multer\(",
            r"upload\.single\(",
            r"upload\.array\(",
        ],
        "sanitizer_patterns": [
            r"secure_filename",
            r"allowed_file",
            r"mime",
            r"extension_check",
            r"validate_file",
        ],
        "vuln_desc": "File upload without proper validation",
        "safe_desc": "File uploads validated with secure filename and type checks",
        "severity": "HIGH",
        "confidence": 75,
        "cwe": "CWE-434"
    },
]